const PLAYER_COUNT = 6;
const builtInWords = ['Sun', 'Teacher', 'Coffee', 'Beach', 'Pizza', 'Doctor', 'Cat', 'Plane', 'Guitar', 'Winter', 'Apple', 'Book', 'Football', 'Camera', 'Volcano', 'Chess', 'Laptop', 'Mountain'];
const keys = { names: 'chameleon.names', words: 'chameleon.customWords', legacyPairs: 'chameleon.customPairs', scores: 'chameleon.scores', history: 'chameleon.history', sound: 'chameleon.soundMuted' };
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
let state = { names: load(keys.names, Array.from({ length: PLAYER_COUNT }, (_, i) => `Player ${i + 1}`)), words: loadWords(), scores: load(keys.scores, null), history: load(keys.history, []), muted: load(keys.sound, false), round: null, selectedWinners: new Set() };
if (!state.scores) state.scores = state.names.map(name => ({ name, games: 0, wins: 0 }));
syncScoreNames();
function load(k, f) { try { return JSON.parse(localStorage.getItem(k)) ?? f; } catch { return f; } }
function save(k, v) { localStorage.setItem(k, JSON.stringify(v)); }
function loadWords() {
  const words = load(keys.words, null);
  if (Array.isArray(words)) return words;
  const legacyPairs = load(keys.legacyPairs, []);
  const migrated = Array.isArray(legacyPairs) ? legacyPairs.map(pair => pair.common).filter(Boolean) : [];
  save(keys.words, migrated);
  return migrated;
}
function cryptoIndex(max) { const a = new Uint32Array(1); crypto.getRandomValues(a); return a[0] % max; }
function shuffle(a) { for (let i = a.length - 1; i > 0; i--) { const j = cryptoIndex(i + 1); [a[i], a[j]] = [a[j], a[i]]; } return a; }
function beep() { if (state.muted) return; const c = new AudioContext(); const o = c.createOscillator(); const g = c.createGain(); o.connect(g); g.connect(c.destination); g.gain.value = .04; o.frequency.value = 660; o.start(); o.stop(c.currentTime + .08); }
function show(id) { $$('.screen').forEach(s => s.classList.toggle('active', s.id === id)); if (id === 'scoreboard') renderScores(); if (id === 'words') renderWords(); if (id === 'statistics') renderStats(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function syncScoreNames() { state.scores = state.names.map((name, i) => ({ name, games: state.scores?.[i]?.games || 0, wins: state.scores?.[i]?.wins || 0 })); save(keys.scores, state.scores); }
function renderNames() { const f = $('#namesForm'); f.innerHTML = ''; state.names.forEach((n, i) => { const label = document.createElement('label'); label.className = 'field name-row'; label.textContent = `Player ${i + 1}`; const input = document.createElement('input'); input.value = n; input.maxLength = 24; input.dataset.nameIndex = i; label.append(input); f.append(label); }); }
function renderPreview() { const n = +$('#imposterCount').value; $('#setupPreview').textContent = `${PLAYER_COUNT - n} Common Players receive the same word + ${n} Imposter${n > 1 ? 's' : ''} receive only “IMPOSTER”. ${builtInWords.length + state.words.length} words available.`; }
function startRound() { const imposterCount = +$('#imposterCount').value; const pool = [...builtInWords, ...state.words]; const secretWord = pool[cryptoIndex(pool.length)]; const imposters = new Set(shuffle([...Array(PLAYER_COUNT).keys()]).slice(0, imposterCount)); state.round = { secretWord, imposters: [...imposters], index: 0, assignments: state.names.map((name, i) => ({ name, word: imposters.has(i) ? 'IMPOSTER' : secretWord, role: imposters.has(i) ? 'Imposter' : 'Common' })), imposterCount }; state.selectedWinners.clear(); renderReveal(); show('reveal'); }
function renderReveal() { const r = state.round; const p = r.assignments[r.index]; const isImposter = p.role === 'Imposter'; $('#currentPlayerName').textContent = p.name; $('#secretWordLabel').textContent = isImposter ? '⚠ YOU ARE THE IMPOSTER' : 'YOUR WORD'; $('#secretWord').textContent = p.word; $('#flipCard').classList.remove('revealed', 'imposter-reveal'); $('#flipCard').classList.toggle('is-imposter', isImposter); $('#hideWordButton').disabled = true; $('#nextPlayerButton').disabled = true; $('#revealProgress').textContent = `Player ${r.index + 1} of ${PLAYER_COUNT}`; }
function reveal() { const card = $('#flipCard'); if (card.classList.contains('revealed')) return; card.classList.add('revealed'); if (card.classList.contains('is-imposter')) card.classList.add('imposter-reveal'); $('#hideWordButton').disabled = false; beep(); }
function hide() { const card = $('#flipCard'); card.classList.remove('revealed', 'imposter-reveal'); $('#hideWordButton').disabled = true; setTimeout(() => { $('#nextPlayerButton').disabled = false; }, 650); }
function nextPlayer() { if ($('#flipCard').classList.contains('revealed')) return; if (state.round.index < PLAYER_COUNT - 1) { state.round.index++; renderReveal(); } else { renderWinner(); show('winner'); } }
function renderWinner() { const box = $('#winnerButtons'); box.innerHTML = ''; state.selectedWinners.clear(); state.names.forEach((name, i) => { const b = document.createElement('button'); b.className = 'secondary winner-choice'; b.textContent = name; b.onclick = () => { state.selectedWinners.has(i) ? state.selectedWinners.delete(i) : state.selectedWinners.add(i); b.classList.toggle('selected'); }; box.append(b); }); const none = document.createElement('button'); none.className = 'secondary winner-choice'; none.textContent = 'No Winner'; none.onclick = () => { state.selectedWinners.clear(); $$('.winner-choice').forEach(b => b.classList.remove('selected')); none.classList.add('selected'); }; box.append(none); }
function saveResult() { const winners = [...state.selectedWinners]; state.scores.forEach((s, i) => { s.games++; if (winners.includes(i)) s.wins++; }); state.history.push({ date: new Date().toISOString(), winners, imposters: state.round.imposterCount }); save(keys.scores, state.scores); save(keys.history, state.history); show('scoreboard'); }
function addWord(e) { e.preventDefault(); const word = $('#customWord').value.trim(); if (!word) return; state.words.push(word); save(keys.words, state.words); e.target.reset(); renderPreview(); renderWords(); }
function renderWords() { const box = $('#customWordsList'); box.innerHTML = state.words.length ? '' : '<p class="muted">No custom words yet.</p>'; state.words.forEach((word, index) => { const row = document.createElement('div'); row.className = 'word-row'; row.innerHTML = `<input value="${escapeHtml(word)}" aria-label="Custom word"><button class="secondary">Save</button><button class="danger">Delete</button>`; const [input, saveBtn, delBtn] = row.children; saveBtn.onclick = () => { state.words[index] = input.value.trim() || state.words[index]; save(keys.words, state.words); renderPreview(); }; delBtn.onclick = () => { state.words.splice(index, 1); save(keys.words, state.words); renderWords(); renderPreview(); }; box.append(row); }); }
function escapeHtml(s) { return s.replace(/[&<>"]/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[m])); }
function renderScores() { const rows = $('#scoreRows'); rows.innerHTML = ''; state.scores.forEach(s => { const pct = s.games ? Math.round(s.wins / s.games * 100) : 0; rows.insertAdjacentHTML('beforeend', `<tr><td>${escapeHtml(s.name)}</td><td>${s.games}</td><td>${s.wins}</td><td>${pct}%</td></tr>`); }); }
function renderStats() { const total = state.history.length; const maxWins = Math.max(0, ...state.scores.map(s => s.wins)); const frequent = state.scores.filter(s => s.wins === maxWins && maxWins).map(s => s.name).join(', ') || 'None'; const last = state.history.at(-1)?.winners || []; const streak = last.length ? last.map(i => state.names[i]).join(', ') : 'No active streak'; const best = [...state.scores].sort((a, b) => (b.games ? b.wins / b.games : 0) - (a.games ? a.wins / a.games : 0))[0]; const avg = total ? (state.history.reduce((a, h) => a + h.imposters, 0) / total).toFixed(1) : '0'; const cards = [['Total rounds played', total], ['Total custom words', state.words.length], ['Most frequent winner(s)', frequent], ['Current win streak', streak], ['Highest overall win rate', best ? `${best.name} (${best.games ? Math.round(best.wins / best.games * 100) : 0}%)` : 'None'], ['Average imposters per game', avg]]; $('#statsGrid').innerHTML = cards.map(([l, v]) => `<div class="stat-card"><span>${l}</span><strong>${v}</strong></div>`).join(''); }
function exportCsv() { const csv = ['Player,Games,Wins,Win %', ...state.scores.map(s => `${s.name},${s.games},${s.wins},${s.games ? Math.round(s.wins / s.games * 100) : 0}%`)].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'chameleon-scoreboard.csv'; a.click(); URL.revokeObjectURL(a.href); }
$$('.nav-button').forEach(b => b.onclick = () => show(b.dataset.screen)); $('#imposterCount').onchange = renderPreview; $('#shuffleButton').onclick = () => { renderPreview(); beep(); }; $('#startGameButton').onclick = startRound; $('#wordForm').onsubmit = addWord; $('#saveNamesButton').onclick = () => { state.names = $$('[data-name-index]').map((i, idx) => i.value.trim() || `Player ${idx + 1}`); save(keys.names, state.names); syncScoreNames(); renderPreview(); beep(); }; $('#flipCard').onclick = reveal; $('#flipCard').onkeydown = e => { if (e.key === 'Enter' || e.key === ' ') reveal(); }; $('#hideWordButton').onclick = hide; $('#nextPlayerButton').onclick = nextPlayer; $('#saveResultButton').onclick = saveResult; $('#newGameFromScoreButton').onclick = () => show('setup'); $('#exportCsvButton').onclick = exportCsv; $('#resetScoreButton').onclick = () => { if (confirm('Reset the entire scoreboard?')) { state.scores = state.names.map(name => ({ name, games: 0, wins: 0 })); state.history = []; save(keys.scores, state.scores); save(keys.history, state.history); renderScores(); } }; $('#clearWordsButton').onclick = () => { if (confirm('Delete all custom words?')) { state.words = []; save(keys.words, state.words); renderWords(); renderPreview(); } }; $('#soundToggle').onclick = () => { state.muted = !state.muted; save(keys.sound, state.muted); $('#soundToggle').textContent = state.muted ? '🔇 Muted' : '🔊 Sound'; $('#soundToggle').setAttribute('aria-pressed', String(!state.muted)); };
renderNames(); renderPreview(); $('#soundToggle').textContent = state.muted ? '🔇 Muted' : '🔊 Sound';
