import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { QRCodeSVG } from 'qrcode.react';
import confetti from 'canvas-confetti';
import { getWordPool, expandedWordCount } from './data/words.js';
import { auth, ensureUser, saveName, roomCode, roomRef, playersRef, playerRef, voteRef, customWordsRef, customWordRef, votesRef, listen, serverTimestamp, setDoc, updateDoc, runTransaction } from './services/firebase.js';
import { useSound } from './hooks/useSound.js';
import './styles.css';

const limits = n => n < 6 ? [1] : n < 9 ? [1, 2] : [1, 2, 3];
const safe = t => String(t || '').trim().slice(0, 28);
const shuffle = a => { const x = [...a]; for (let i = x.length - 1; i > 0; i--) { const j = crypto.getRandomValues(new Uint32Array(1))[0] % (i + 1); [x[i], x[j]] = [x[j], x[i]]; } return x; };

function App() {
  const [user, setUser] = useState(null); const [screen, setScreen] = useState('home'); const [code, setCode] = useState('');
  const [room, setRoom] = useState(null); const [players, setPlayers] = useState([]); const [votes, setVotes] = useState([]); const [me, setMe] = useState(null);
  const [nickname, setNickname] = useState(localStorage.getItem('imposter.nickname') || ''); const [settings, setSettings] = useState({ playerCount: 6, imposters: 1, words: 'builtin', timer: 0 });
  const [customWords, setCustomWords] = useState(() => JSON.parse(localStorage.getItem('imposter.customWords') || '[]')); const [selected, setSelected] = useState([]); const [error, setError] = useState('');
  const { muted, toggle, play } = useSound();

  useEffect(() => { ensureUser().then(setUser); }, []);
  useEffect(() => { if (!code) return; const a = listen(roomRef(code), s => setRoom(s.exists() ? { id: s.id, ...s.data() } : null)); const b = listen(playersRef(code), s => setPlayers(s.docs.map(d => ({ id: d.id, ...d.data() })).sort((x, y) => (x.joinedAt?.seconds || 0) - (y.joinedAt?.seconds || 0)))); return () => { a(); b(); };  }, [code]);
  useEffect(() => { if (!code || !auth.currentUser?.uid) return; return listen(voteRef(code, auth.currentUser.uid), s => setMe(s.exists() ? s.data() : null)); }, [code]);
  useEffect(() => { if (!code) return; return listen(votesRef(code), s => setVotes(s.docs.map(d => d.data()))); }, [code]);
  useEffect(() => { if (!user) return listen(customWordsRef(user.uid), s => { const words = s.docs.map(d => d.data().word); setCustomWords(words); localStorage.setItem('imposter.customWords', JSON.stringify(words)); }); }, [user]);

  const isHost = room?.hostId === user?.uid; const myPlayer = players.find(p => p.id === user?.uid);
  const stats = useMemo(() => computeStats(players, room, customWords), [players, room, customWords]);
  async function createGame() { setError(''); const u = user || await ensureUser(); const name = safe(nickname) || 'Host'; localStorage.setItem('imposter.nickname', name); await saveName(name); const newCode = roomCode(); await setDoc(roomRef(newCode), { hostId: u.uid, code: newCode, status: 'lobby', settings, createdAt: serverTimestamp(), round: 0, usedWords: [], history: [], startedAt: null }); await setDoc(playerRef(newCode, u.uid), profile(name, true)); setCode(newCode); setScreen('lobby'); play('join'); }
  async function joinGame() { setError(''); const u = user || await ensureUser(); const name = safe(nickname); const c = safe(code).toUpperCase(); if (!name || c.length !== 6) return setError('Enter a nickname and 6-character room code.'); await runTransaction(roomRef(c).firestore, async tx => { const r = await tx.get(roomRef(c)); if (!r.exists()) throw new Error('Room not found.'); const p = await tx.get(playerRef(c, u.uid)); if (!p.exists()) tx.set(playerRef(c, u.uid), profile(name, false)); return r.data(); }); localStorage.setItem('imposter.nickname', name); await saveName(name); setCode(c); setScreen('lobby'); play('join'); }
  async function startRound() { const pool = getWordPool(settings.words === 'custom' ? customWords : []); const unused = pool.filter(w => !room.usedWords?.includes(`${w.category}:${w.word}`)); const word = shuffle(unused.length ? unused : pool)[0]; const imposters = new Set(shuffle(players.map(p => p.id)).slice(0, settings.imposters)); await Promise.all(players.map(p => updateDoc(playerRef(code, p.id), { role: imposters.has(p.id) ? 'imposter' : 'player', category: word.category, word: imposters.has(p.id) ? null : word.word, confirmed: false, voteFor: null }))); await updateDoc(roomRef(code), { status: 'reveal', settings, secretCategory: word.category, secretWordLocked: true, usedWords: [...(unused.length ? room.usedWords || [] : []), `${word.category}:${word.word}`], startedAt: Date.now(), round: (room.round || 0) + 1 }); play('start'); }
  async function confirmRole() { await updateDoc(playerRef(code, user.uid), { confirmed: true }); if (players.every(p => p.id === user.uid || p.confirmed)) await updateDoc(roomRef(code), { status: 'discussion', discussionStartedAt: Date.now() }); play('reveal'); }
  async function castVote(id) { await setDoc(voteRef(code, user.uid), { voter: user.uid, target: id, at: serverTimestamp() }); play('vote'); }
  async function saveResult() { const winners = selected; const next = players.map(p => ({ ...p, games: (p.games || 0) + 1, wins: (p.wins || 0) + (winners.includes(p.id) ? 1 : 0), streak: winners.includes(p.id) ? (p.streak || 0) + 1 : 0, longest: Math.max(p.longest || 0, winners.includes(p.id) ? (p.streak || 0) + 1 : 0) })); await Promise.all(next.map(p => updateDoc(playerRef(code, p.id), { games: p.games, wins: p.wins, streak: p.streak, longest: p.longest }))); await updateDoc(roomRef(code), { status: 'scoreboard', history: [...(room.history || []), { winners, imposters: settings.imposters, category: room.secretCategory, duration: Date.now() - (room.startedAt || Date.now()) }] }); confetti(); play('winner'); }
    const nav = ['home','create','join','words','statistics'];
  return <div className="app"><div className="bg"/><header className="top glass"><button onClick={() => setScreen('home')} className="brand">IMPOSTER</button><nav>{nav.map(n => <button key={n} onClick={() => setScreen(n)}>{n}</button>)}<button onClick={toggle}>{muted ? '🔇' : '🔊'}</button></nav></header>{error && <p className="error">{error}</p>}<AnimatePresence mode="wait"><motion.main key={screen + room?.status} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-18}}>
    {screen==='home' && <Home setScreen={setScreen}/>} {screen==='create' && <Create settings={settings} setSettings={setSettings} createGame={createGame}/>} {screen==='join' && <Join nickname={nickname} setNickname={setNickname} code={code} setCode={setCode} joinGame={joinGame}/>} {screen==='lobby' && <Lobby code={code} room={room} players={players} isHost={isHost} settings={settings} startRound={startRound} setScreen={setScreen}/>} {screen==='words' && <Words user={user} customWords={customWords}/>} {screen==='statistics' && <Statistics stats={stats}/>} {room?.status==='reveal' && <Role me={myPlayer} confirmRole={confirmRole}/>} {room?.status==='discussion' && <Discussion room={room} players={players} isHost={isHost} code={code}/>} {room?.status==='voting' && <Voting players={players} votes={votes} castVote={castVote} isHost={isHost} setSelected={setSelected} selected={selected} saveResult={saveResult}/>} {room?.status==='scoreboard' && <Scoreboard players={players} setScreen={setScreen}/>} </motion.main></AnimatePresence></div>;
}
function profile(name, host) { return { name, host, joinedAt: serverTimestamp(), games: 0, wins: 0, streak: 0, longest: 0 }; }
function Home({setScreen}) { return <section className="hero glass"><p>The ultimate social deduction game.</p><h1>IMPOSTER</h1><div className="actions"><button className="primary" onClick={()=>setScreen('create')}>Create Game</button><button onClick={()=>setScreen('join')}>Join Game</button><button onClick={()=>setScreen('statistics')}>Statistics</button><button onClick={()=>setScreen('words')}>Settings</button></div></section>; }
function Create({settings,setSettings,createGame}) { const opts = limits(settings.playerCount); return <section className="card glass"><h2>Create Game</h2><label>Number of Players<input type="range" min="4" max="12" value={settings.playerCount} onChange={e=>setSettings({...settings, playerCount:+e.target.value, imposters: limits(+e.target.value)[0]})}/><b>{settings.playerCount}</b></label><label>Number of Imposters<select value={settings.imposters} onChange={e=>setSettings({...settings, imposters:+e.target.value})}>{opts.map(o=><option key={o} value={o}>{o}</option>)}</select></label><label>Words<select value={settings.words} onChange={e=>setSettings({...settings, words:e.target.value})}><option value="builtin">Built-in Words Only</option><option value="custom">Built-in + Custom Words</option></select></label><label>Discussion Timer<select value={settings.timer} onChange={e=>setSettings({...settings,timer:+e.target.value})}><option value="0">Off</option><option value="120">2 Minutes</option><option value="180">3 Minutes</option><option value="300">5 Minutes</option></select></label><button className="primary" onClick={createGame}>Start Lobby</button></section>; }
function Join(p) { return <section className="card glass"><h2>Join Game</h2><input placeholder="Nickname" value={p.nickname} onChange={e=>p.setNickname(e.target.value)}/><input placeholder="Room Code" value={p.code} onChange={e=>p.setCode(e.target.value.toUpperCase())}/><button className="primary" onClick={p.joinGame}>Enter Lobby</button></section>; }
function Lobby({code,players,isHost,settings,startRound}) { const full = players.length >= settings.playerCount; return <section className="card glass"><h2>Lobby</h2><div className="code">{code}</div><QRCodeSVG value={`${location.origin}?room=${code}`} bgColor="transparent" fgColor="#fff"/><h3>{players.length} / {settings.playerCount} Joined</h3>{players.map(p=><p key={p.id}>{p.host?'Host · ':''}{p.name}</p>)}{Array.from({length:Math.max(0,settings.playerCount-players.length)}).map((_,i)=><p className="muted" key={i}>Waiting...</p>)}{isHost && <button disabled={!full} className="primary" onClick={startRound}>Start Game</button>}</section>; }
function Role({me,confirmRole}) { if (!me) return null; return <section className="role glass"><p>CATEGORY</p><h2>{me.category}</h2>{me.role==='imposter'?<><p>YOU ARE THE IMPOSTER</p><h1 className="dangerText">IMPOSTER</h1></>:<><p>YOUR WORD</p><h1>{me.word}</h1></>}<button className="primary" onClick={confirmRole}>I Understand</button></section>; }
function Discussion({room,players,isHost,code}) { const all = players.every(p=>p.confirmed); return <section className="card glass"><h2>Everyone has received their role.</h2><p>Discuss face to face. Describe your word without saying it. Find the Imposter.</p>{room.settings?.timer ? <p className="timer">Timer: {Math.ceil(room.settings.timer/60)} minutes</p> : <p>Timer off</p>}{isHost && all && <button className="primary" onClick={()=>updateDoc(roomRef(code),{status:'voting'})}>Start Voting</button>}</section>; }
function Voting({players,votes,castVote,isHost,selected,setSelected,saveResult}) { const complete = votes.length >= players.length; return <section className="card glass"><h2>Vote</h2>{players.map(p=><button key={p.id} onClick={()=>castVote(p.id)}>{p.name}</button>)}{isHost && complete && <><h3>Voting Complete. Select winners.</h3><div className="grid">{players.map(p=><button className={selected.includes(p.id)?'selected':''} onClick={()=>setSelected(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])} key={p.id}>{p.name}</button>)}<button onClick={()=>setSelected([])}>No Winner</button></div><button className="primary" onClick={saveResult}>Save Result</button></>}</section>; }
function Scoreboard({players,setScreen}) { return <section className="card glass"><h2>Persistent Scoreboard</h2><table><tbody>{players.sort((a,b)=>b.wins-a.wins).map((p,i)=><tr key={p.id}><td>{['🥇','🥈','🥉'][i]||''} {p.name}</td><td>{p.games} games</td><td>{p.wins} wins</td><td>{p.games?Math.round(p.wins/p.games*100):0}%</td><td>🔥 {p.streak||0}</td></tr>)}</tbody></table><button className="primary" onClick={()=>setScreen('lobby')}>Next Round</button></section>; }
function Words({user,customWords}) { const [word,setWord]=useState(''); async function add(){ if(!user||!safe(word))return; await setDoc(customWordRef(user.uid, crypto.randomUUID()), { word:safe(word), category:'INSIDER BALL KNOWLEDGE', createdAt:serverTimestamp()}); setWord(''); } return <section className="card glass"><h2>Custom Words</h2><p>Built-in words available: {expandedWordCount * 3}. Custom words use category INSIDER BALL KNOWLEDGE.</p><input value={word} onChange={e=>setWord(e.target.value)} placeholder="Virat Kohli"/><button onClick={add}>Add</button><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(customWords,null,2))}>Export</button>{customWords.map(w=><p key={w}>{w}</p>)}</section>; }
function Statistics({stats}) { return <section className="card glass"><h2>Statistics</h2><div className="stats">{Object.entries(stats).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div></section>; }
function computeStats(players, room, customWords) { const h=room?.history||[]; const best=[...players].sort((a,b)=>(b.wins||0)-(a.wins||0))[0]; return {'Total Games':h.length,'Total Custom Words':customWords.length,'Total Built-in Words':expandedWordCount*3,'Most Successful Player':best?.name||'None','Highest Win %':best?.games?`${Math.round(best.wins/best.games*100)}%`:'0%','Longest Win Streak':Math.max(0,...players.map(p=>p.longest||0)),'1 Imposter Games':h.filter(x=>x.imposters===1).length,'2 Imposter Games':h.filter(x=>x.imposters===2).length,'3 Imposter Games':h.filter(x=>x.imposters===3).length,'Average Game Length':h.length?`${Math.round(h.reduce((a,x)=>a+(x.duration||0),0)/h.length/1000)}s`:'0s','Most Used Category':h.at(-1)?.category||'None'}; }
createRoot(document.getElementById('root')).render(<App />);
